"""Added tables.

Revision ID: 30f48ac5fc69
Revises: 
Create Date: 2021-09-23 01:06:57.725310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f48ac5fc69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxiv_queries',
    sa.Column('arxiv_query_id', sa.Integer(), nullable=False),
    sa.Column('arxiv_query', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('arxiv_query_id', name=op.f('pk_arxiv_queries')),
    sa.UniqueConstraint('arxiv_query', name=op.f('uq_arxiv_queries_arxiv_query'))
    )
    op.create_table('papers',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('abstract', sa.TEXT(), nullable=False),
    sa.Column('abstract_jp', sa.TEXT(), nullable=False),
    sa.Column('pdf_link', sa.TEXT(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('is_stocked', sa.Boolean(), nullable=False),
    sa.Column('arxiv_query_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arxiv_query_id'], ['arxiv_queries.arxiv_query_id'], name=op.f('fk_papers_arxiv_query_id_arxiv_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', name=op.f('pk_papers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('papers')
    op.drop_table('arxiv_queries')
    # ### end Alembic commands ###
