"""Add publiched_at column

Revision ID: 40d6bdb5cb77
Revises: 5d8c9b5cc038
Create Date: 2021-09-22 17:01:48.679565

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '40d6bdb5cb77'
down_revision = '5d8c9b5cc038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('published_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'published_at')
    # ### end Alembic commands ###
