"""Add published date

Revision ID: 57503e0dbe9b
Revises: 5d8c9b5cc038
Create Date: 2021-09-20 16:56:19.322876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57503e0dbe9b'
down_revision = '5d8c9b5cc038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('published_at', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'published_at')
    # ### end Alembic commands ###
