"""Added tables.

Revision ID: a2fa793538c6
Revises: 
Create Date: 2021-09-16 18:00:45.022292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fa793538c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxiv_queries',
    sa.Column('arxiv_query_id', sa.Integer(), nullable=False),
    sa.Column('arxiv_query', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('arxiv_query_id', name=op.f('pk_arxiv_queries')),
    sa.UniqueConstraint('arxiv_query', name=op.f('uq_arxiv_queries_arxiv_query'))
    )
    op.create_table('papers',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('abstract', sa.TEXT(), nullable=False),
    sa.Column('abstract_jp', sa.TEXT(), nullable=False),
    sa.Column('pdf_link', sa.TEXT(), nullable=False),
    sa.Column('arxiv_query_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arxiv_query_id'], ['arxiv_queries.arxiv_query_id'], name=op.f('fk_papers_arxiv_query_id_arxiv_queries')),
    sa.PrimaryKeyConstraint('paper_id', name=op.f('pk_papers'))
    )
    op.create_table('paper_stocks',
    sa.Column('paper_stock_id', sa.Integer(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name=op.f('fk_paper_stocks_paper_id_papers')),
    sa.PrimaryKeyConstraint('paper_stock_id', name=op.f('pk_paper_stocks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_stocks')
    op.drop_table('papers')
    op.drop_table('arxiv_queries')
    # ### end Alembic commands ###
