"""Create papers queries favorites tables

Revision ID: 175285e31a56
Revises: 
Create Date: 2021-09-13 21:31:50.315769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175285e31a56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('is_delted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queries')),
    sa.UniqueConstraint('query', name=op.f('uq_queries_query'))
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('abstract', sa.TEXT(), nullable=False),
    sa.Column('link', sa.TEXT(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], name=op.f('fk_papers_query_id_queries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers'))
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_favorites_paper_id_papers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('papers')
    op.drop_table('queries')
    # ### end Alembic commands ###
