# [Choice] Python version: 3, 3.8, 3.7, 3.6
ARG VARIANT=3.8
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

ENV PYTHONUNBUFFERED 1

# Update args in docker-compose.yaml to set the UID/GID of the "vscode" user.
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN if [ "$USER_GID" != "1000" ] || [ "$USER_UID" != "1000" ]; then groupmod --gid $USER_GID vscode && usermod --uid $USER_UID --gid $USER_GID vscode; fi

# [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
ARG NODE_VERSION="none"
RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

COPY app/pyproject.toml app/poetry.lock /tmp/pip-tmp/

WORKDIR /tmp/pip-tmp/

RUN pip install poetry \
   && poetry config virtualenvs.create false \
   && poetry install \
   && rm -rf /tmp/pip-tmp

WORKDIR  /var/log/gunicorn
RUN chown -R vscode /var/log/gunicorn

ENV TZ Asia/Tokyo
ENV PYTHONPATH "${PYTHONPATH}:/workspace"
