version: "3"

services:
  app:
    image: paperlibrary:latest
    container_name: app
    build:
      context: ..
      dockerfile: .docker/Dockerfile

    command: ["gunicorn", "-w", "2", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000", "main:app", "--log-config", "logging.conf"]
    env_file: app.env

    volumes:
      - ./log:/var/log/gunicorn

  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: app.env

  web:
    container_name: web
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/ssl:/etc/nginx/ssl
      - ./web/build:/usr/share/nginx/build

volumes:
  postgres-data:
